
CREATE TABLE product
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text COLLATE pg_catalog."default" NOT NULL,
    slogan text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    default_price text COLLATE pg_catalog."default" NOT NULL

);

CREATE TABLE styles
(
     stylesId int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    sale_price text COLLATE pg_catalog."default",
    original_price text COLLATE pg_catalog."default" NOT NULL,
    default_style integer NOT NULL,
    CONSTRAINT product_id FOREIGN KEY (product_id)
        REFERENCES product (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID
);


CREATE TABLE features
(
    featuresId int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer,
    feature character varying(200) COLLATE pg_catalog."default",
    value character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT product_id FOREIGN KEY (product_id)
        REFERENCES product (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID
);

CREATE TABLE photos
(
     photosId int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    styles_id integer,
    url text COLLATE pg_catalog."default" NOT NULL,
    thumbnail_url text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT styles_id FOREIGN KEY (styles_id)
        REFERENCES styles (stylesId) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);



CREATE TABLE skus
(
    skusId int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    styles_id integer,
    size character varying(5) COLLATE pg_catalog."default",
    quantity integer,
    CONSTRAINT styles_id FOREIGN KEY (styles_id)
        REFERENCES styles (stylesId) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID
);

\COPY product FROM
'/home/ec2-user/product_detail_RW/database/product.csv'
DELIMITER ','
CSV HEADER;

\COPY features FROM '/home/ec2-user/product_detail_RW/database/features.csv'
DELIMITER ','
CSV HEADER;


\copy features FROM '/home/ec2-user/product_detail_RW/database/features.csv' DELIMITER ',' CSV

\COPY features FROM '/home/ec2-user/product_detail_RW/database/features.csv'
DELIMITER ','
CSV HEADER;

\COPY styles FROM '/home/ec2-user/product_detail_RW/database/styles.csv'
DELIMITER ','
CSV HEADER;

\COPY skus FROM '/home/ec2-user/product_detail_RW/database/skus.csv'
DELIMITER ','
CSV HEADER;

\COPY photos FROM '/home/ec2-user/product_detail_RW/database/photos.csv'
DELIMITER ','
CSV HEADER;


\COPY product FROM '/Users/ryanweaver/hackreactor/SDC/product-detail/database/product.csv'
DELIMITER ','
CSV HEADER;



COPY features FROM '/Users/ryanweaver/hackreactor/SDC/product-detail/database/features.csv'
DELIMITER ','
CSV HEADER;

COPY styles FROM '/Users/ryanweaver/hackreactor/SDC/product-detail/database/styles.csv'
DELIMITER ','
CSV HEADER;

COPY skus FROM '/Users/ryanweaver/hackreactor/SDC/product-detail/database/skus.csv'
DELIMITER ','
CSV HEADER;

COPY photos FROM '/Users/ryanweaver/hackreactor/SDC/product-detail/database/photos.csv'
DELIMITER ','
CSV HEADER;



CREATE INDEX product_index ON product (id);
CREATE INDEX styles_index ON styles (product_id);

CREATE INDEX features_index ON features (product_id)

CREATE INDEX skus_index ON skus (styles_id);
CREATE INDEX photos_index ON photos (styles_id);